#!/bin/bash
### Subscribe to my YouTube channel to support me => [ https://www.youtube.com/@techghoshal ] ###
echo
echo " 🤖️ Hi there! How can I help you?"
while true;
do
    echo
    read -p " 🧒️  " chat
    mod=${chat// /+}
    echo
    #API KEY
    OPENAI_API_KEY="API_KEY"
    #API request
    res=$(curl https://api.openai.com/v1/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $OPENAI_API_KEY" \
        -d '{
  "model": "text-davinci-003",
  "prompt": "'+$mod+':\nA:",
  "temperature": 0,
  "max_tokens": 100,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.0,
  "stop": ["\n"]
    }' -s)
    ##Filter JSON data
    #Fetching finish_reason
    fReason=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.finish_reason' | tr -d '"')
    #Checking on text that the text is empty or not empty
    empty=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.text')
    #check error
    error=$(echo $res |  grep error | cut -d " " -f 2 | tr -d '"' | tr -d ":" )

    #Check error condition
    if [ "$error" == "error" ]
    then
        echo " 🤖️ Somthing went Worng! Please try again "
        echo
        echo $res | tr -d "{","}"
        #Check text vlaue is empty or not empty condition
    elif [ "$empty" == '""' ]
    then
        echo ' 🤖️ Somthing went Worng! AI did not reply [ text":"_blank" ] '
        echo
        echo $res
    #Check fReason condition 
    elif [ "$fReason" == "stop" ]
    then
        ans=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.text' | tr -d '"')
        echo " 🤖️" $ans
    else
        echo " Somthing went Worng! Please try again "
    fi
done
