#!/bin/bash
### Subscribe to my YouTube channel to support me => [ https://www.youtube.com/@techghoshal ] ###
echo
#SET API KEY
OPENAI_API_KEY="API_KEY"

echo " 🤖️ Hi there! How can I help you?"
while true;
do
    echo
    read -p " 🧒️  " chat
    #encode special characters
    n="${#chat}"
    mod=$chat
    i=0
    while (( i<=$n ));
    do
        char="${chat:$i:1}"
        
        if [ "$char" == " " ]
        then
            mod=${mod// /%20}
        elif [ "$char" == "!" ]
        then
            mod=${mod//!/%21}
        elif [ "$char" == '"' ]
        then
            mod=${mod//'"'/%22}
        elif [ "$char" == "#" ]
        then
            mod=${mod//#/%23}
        elif [ "$char" == "$" ]
        then
            mod=${mod//"$"/%24}
        elif [ "$char" == "%" ]
        then
            mod=${mod//"%"/%25}
        elif [ "$char" == "&" ]
        then
            mod=${mod//"&"/%26}
        elif [ "$char" == "'" ]
        then
            mod=${mod//"'"/%27}
        elif [ "$char" == "(" ]
        then
            mod=${mod//"("/%28}
        elif [ "$char" == ")" ]
        then
            mod=${mod//")"/%29}
        elif [ "$char" == "+" ]
        then
            mod=${mod//"+"/%2B}
        elif [ "$char" == "," ]
        then
            mod=${mod//","/%2C}
        elif [ "$char" == "-" ]
        then
            mod=${mod//"-"/%2D}
        elif [ "$char" == "." ]
        then
            mod=${mod//"."/%2E}
        elif [ "$char" == ":" ]
        then
            mod=${mod//":"/%3A}
        elif [ "$char" == ";" ]
        then
            mod=${mod//";"/%3B}
        elif [ "$char" == "<" ]
        then
            mod=${mod//"<"/%3C}
        elif [ "$char" == "=" ]
        then
            mod=${mod//"="/%3D}
        elif [ "$char" == ">" ]
        then
            mod=${mod//">"/%3E}
        elif [ "$char" == "?" ]
        then
            mod=${mod//"?"/%3F}
        elif [ "$char" == "@" ]
        then
            mod=${mod//"@"/%40}
        elif [ "$char" == "<" ]
        then
            mod=${mod//</%3C}
        elif [ "$char" == "[" ]
        then
            mod=${mod//"["/%5B}
        elif [ "$char" == '\' ]
        then
            mod=${mod//'\'/%5C}
        elif [ "$char" == "]" ]
        then
            mod=${mod//"]"/%5D}
        elif [ "$char" == "^" ]
        then
            mod=${mod//"^"/%5E}
        elif [ "$char" == "_" ]
        then
            mod=${mod//"_"/%5F}
        elif [ "$char" == '`' ]
        then
            mod=${mod//'`'/%60}
        elif [ "$char" == "{" ]
        then
            mod=${mod//"{"/%7B}
        elif [ "$char" == "|" ]
        then
            mod=${mod//"|"/%7C}
        elif [ "$char" == "}" ]
        then
            mod=${mod//"}"/%7D}
        elif [ "$char" == "~" ]
        then
            mod=${mod//"~"/%7E}
        fi
        
        
        ((i++))
    done
    
    echo
    #API request
    res=$(curl https://api.openai.com/v1/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $OPENAI_API_KEY" \
        -d '{
  "model": "text-davinci-003",
  "prompt": "'$mod'\nA:",
  "temperature": 0,
  "max_tokens": 100,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.0,
  "stop": ["\n"]
    }' -s)
    ##Filter JSON data
    #Fetching finish_reason
    fReason=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.finish_reason' | tr -d '"')
    #Checking on text that the text is empty or not empty
    empty=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.text')
    #check error
    error=$(echo $res |  grep error | cut -d " " -f 2 | tr -d '"' | tr -d ":" )
    
    #Check error condition
    if [ "$error" == "error" ]
    then
        echo " 🤖️ Somthing went Worng! Please try again "
        echo
        echo $res | tr -d "{","}"
        #Check text vlaue is empty or not empty condition
    elif [ "$empty" == '""' ]
    then
        echo ' 🤖️ Somthing went Worng! AI did not reply [ text":"_blank" ] '
        echo
        echo $res
        #Check fReason condition
    elif [ "$fReason" == "stop" ]
    then
        ans=$(echo $res | jq '.choices' | tr -d "[" | tr -d "]" | jq '.text' | tr -d '"')
        echo " 🤖️" $ans
    else
        echo " Somthing went Worng! Please try again "
    fi
done
